set_project("incremental")
includes(path.join(os.getenv("BLUESPEC_XMAKE_ROOT"), "rules", "bluespec.lua"))

target("library")
    set_kind("phony")
    add_rules("bluespec.library")
    set_bsc_root("src/library/Base.bsv")
    add_bsc_package_dirs("src/library", {public = true})

target("consumer")
    set_kind("phony")
    add_rules("bluespec.check")
    set_bsc_root("src/consumer/Consumer.bsv")
    add_deps("library")

target("rtl")
    set_kind("phony")
    set_default(false)
    add_rules("bluespec.verilog")
    set_bsc_root("src/backend/Top.bsv")
    set_bsc_top("mkIncrementalTop")
    add_deps("library")
